import { BrowserWindow, Menu } from "electron";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export class Bezel {
  private mainWindow: BrowserWindow;

  constructor() {
    this.createWindow();
  }

  private createWindow(): void {
    // Create the browser window.
    // Frame false removes the toolbars and menus around the rendered web page
    this.mainWindow = new BrowserWindow({
      height: 600,
      width: 800,
      frame: false,
      transparent: true,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      },
    });

    this.mainWindow.setSkipTaskbar(true);

    // and load the index.html of the app.
    this.mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Menu won't be shown anyway because it's a frameless window,
    // but removing just in case as a default menu is created and might have some random hotkeys we don't want
    Menu.setApplicationMenu(null);
  }
}
