name: Publish tscut
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish tscut to draft release
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install Dependencies
        run: npm i
      - name: Publish tscut for ${{ matrix.os }}
        run: npm run publish
